version: '3.9'
services:
    prisma-studio:
        container_name: prisma-studio
        image: timothyjmiller/prisma-studio:latest
        restart: unless-stopped
        depends_on:
            - postgres
        profiles:
            - dev
        environment:
            # prisma studio requires the env variable name be POSTGRES_URL
            POSTGRES_URL: ${DATABASE_URL}
        ports:
            - ${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}
    postgres:
        image: postgres:12.14
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_USER_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        restart: 'unless-stopped'
        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
    futababot:
        build: .
        container_name: futababot-container
        # Our app does not work without our database
        # so this ensures our database is loaded first
        depends_on:
            - postgres
        tty: true
        env_file:
            - src/.env.development.local
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./:/usr/src/app/
            - node_modules:/user/src/app/node_modules # exclude this directory
volumes:
    postgres-data:
    node_modules:
